### ISSUE TITLE
`yarn start` on Windows causes the snap to be built multiple times, sometimes in an endless loop

### ISSUE THREAD

**Issue by Montoya** [MetaMask/template-snap-monorepo#19] opened 2022-11-15 03:04 UTC
The following behavior is happening on Windows 10 with a fresh copy of the template-snap-monorepo: 

```
C:\Users\sirok\Downloads\template-snap-monorepo-main>yarn start
➤ YN0000: [site]: Process started
➤ YN0000: [snap]: Process started
➤ YN0000: [snap]: Watching '.' for changes...
➤ YN0000: [snap]: Browserslist: caniuse-lite is outdated. Please run:
➤ YN0000: [snap]:   npx browserslist@latest --update-db
➤ YN0000: [snap]:   Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
➤ YN0000: [snap]: Build success: 'src\index.ts' bundled as 'dist\bundle.js'!
➤ YN0000: [snap]: File changed: snap.manifest.json
➤ YN0000: [snap]: Build success: 'src\index.ts' bundled as 'dist\bundle.js'!
➤ YN0000: [snap]: File changed: snap.manifest.json
➤ YN0000: [snap]: Build success: 'src\index.ts' bundled as 'dist\bundle.js'!
➤ YN0000: [snap]: File changed: snap.manifest.json
➤ YN0000: [snap]: Build success: 'src\index.ts' bundled as 'dist\bundle.js'!
➤ YN0000: [snap]: File changed: snap.manifest.json
➤ YN0000: [snap]: Build success: 'src\index.ts' bundled as 'dist\bundle.js'!
➤ YN0000: [snap]: File changed: snap.manifest.json
➤ YN0000: [snap]: Build success: 'src\index.ts' bundled as 'dist\bundle.js'!
➤ YN0000: [snap]: Eval Success: evaluated 'dist\bundle.js' in SES!
➤ YN0000: [snap]:
➤ YN0000: [snap]: Starting server...
➤ YN0000: [snap]: Server listening on: http://localhost:8080
➤ YN0000: [snap]: Eval Success: evaluated 'dist\bundle.js' in SES!
➤ YN0000: [snap]: Eval Success: evaluated 'dist\bundle.js' in SES!
➤ YN0000: [snap]: Eval Success: evaluated 'dist\bundle.js' in SES!
➤ YN0000: [snap]: Eval Success: evaluated 'dist\bundle.js' in SES!
➤ YN0000: [snap]: Eval Success: evaluated 'dist\bundle.js' in SES!
➤ YN0000: [site]: success compile gatsby files - 2.005s
```

For some reason, whatever is watching the snap directory is seeing the snap.manifest.json changing and triggering another build. 

In another snap based on this template, the same thing happens, but it happens over and over in an endless loop.

**Comment by rekmarks** [comment] 2022-11-15 03:23
Suggestions:
- See if replicable with the CLI on Windows, without the template. If so, check for `chokidar` issue.
- Check if other package script / Yarn 3 issue.

**Comment by GuillaumeRx** [comment] 2022-11-15 11:56
Can't reproduce the endless loop on my end but I'm also having a change detected in `snap.manifest.json` even thought nothing has changed.

**Comment by iafi01** [comment] 2022-12-11 12:02
I fixed that installing WSL and using Ubuntu as sub-system, so if you need quickly to move to develop i think that's a good way.
Let me know

**Comment by FrederikBolding** [comment] 2023-02-15 07:36
Closing as this should be fixed by https://github.com/MetaMask/snaps-monorepo/pull/1171 - Please open a new issue if you keep seeing this problem.

**Closed by FrederikBolding** 2023-02-15 07:36 UTC
Labels: bug
